import './globals.css'
import { Montserrat } from 'next/font/google'
import { dir } from 'i18next'
import { languages } from '../i18n/settings'
import Header from './components/Header'
import Footer from './components/Footer'
import { Providers } from './providers'

export const metadata = {
  title: 'Next JS Xac',
  description: 'Generated by create next app',
}
const montserrat = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-montserrat'
});
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={`${montserrat.className} bg-white dark:bg-black`}>
        <Providers>
          <Header lng={lng} />
          {children}
          <Footer lng={lng} />
        </Providers>
      </body>
    </html>
  )
}
